spring:
  application:
    name: SpringLoadBalancer
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://Product
          predicates:
            - Path=/**
server:
  port: 8000